

version: '3.5'

services:

  postgres:
    image: postgres:15.0-alpine
    container_name: pgsql123
    hostname: localhost
    environment:

      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123

    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data
    restart: always

volumes:
  pg_data:
    driver: local
